name: DropXP
main: com.github.wiliansantosbr.dropxp.Main
version: 1.3.1
api-version: 1.20
author: wiliansantosbr
description: Armazene e troque seu XP!
commands:
  dropxp:
    description: Armazena seu XP em uma garrafa
    usage: /dropxp <número de níveis brutos>
    permission: dropxp.drop
  droplvl:
     description: Cria uma garrafa de XP nivelada
     usage: /droplvl <número de níveis>
     permission: dropxp.lvl
permissions:
   dropxp.*:
      description: Dá acesso a todas as funcionalidades do dropxp
      children:
         dropxp.drop: true
         dropxp.drink: true
         dropxp.specify: true
   dropxp.drop:
      description: Permite que você armazene seu XP
      default: true
   dropxp.drink:
      description: Permite que você beba poções de XP
      default: true
   dropxp.specify:
      description: Permite que você perca uma quantidade específica de XP
      default: op
   dropxp.lvl:
      description: Permite que você perca uma quantidade específica de XP
      default: op