name: DropXP
main: com.github.boltydawg.dropxp.Main
version: 1.3.1
api-version: 1.20
author: BoltyDawg
description: Store and trade your XP!
commands:
  dropxp:
    description: Stores your xp in a bottle
    usage: /dropxp <number of raw levels>
    permission: dropxp.drop
  droplvl:
     description: Creates a leveled xp bottle
     usage: /droplvl <number of levels>
     permission: dropxp.lvl
permissions:
   dropxp.*:
      description: Gives access to all dropxp functionality
      children:
         dropxp.drop: true
         dropxp.drink: true
         dropxp.specify: true
   dropxp.drop:
      description: Allows you to store your xp
      default: true
   dropxp.drink:
      description: Allows you to drink xp potions
      default: true
   dropxp.specify:
      description: Allows you to drop a specific amount of xp
      default: op
   dropxp.lvl:
      description: Allows you to generate a potion based off levels rather than orbs
      default: op